// Generated by gencpp from file robot_localization/ToggleFilterProcessingResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGRESPONSE_H
#define ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_localization
{
template <class ContainerAllocator>
struct ToggleFilterProcessingResponse_
{
  typedef ToggleFilterProcessingResponse_<ContainerAllocator> Type;

  ToggleFilterProcessingResponse_()
    : status(false)  {
    }
  ToggleFilterProcessingResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleFilterProcessingResponse_

typedef ::robot_localization::ToggleFilterProcessingResponse_<std::allocator<void> > ToggleFilterProcessingResponse;

typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingResponse > ToggleFilterProcessingResponsePtr;
typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingResponse const> ToggleFilterProcessingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator1> & lhs, const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator1> & lhs, const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_localization/ToggleFilterProcessingResponse";
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleFilterProcessingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_localization::ToggleFilterProcessingResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGRESPONSE_H
